# Generated by Django 4.2.2 on 2023-07-04 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("pub_date", models.DateTimeField()),
                ("content", models.TextField(max_length=2000)),
                (
                    "assignees",
                    models.ManyToManyField(blank=True, related_name="assigned_tickets", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TicketStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(max_length=20, unique=True)),
                ("description", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="TicketComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pub_date", models.DateTimeField()),
                ("content", models.TextField(max_length=2000)),
                (
                    "author",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
                ("ticket", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.ticket")),
            ],
        ),
        migrations.AddField(
            model_name="ticket",
            name="status",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.ticketstatus"),
        ),
    ]
