# Generated by Django 4.2.2 on 2023-07-06 04:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_ticket_created_ticket_modified_ticketcomment_created_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="pub_date",
        ),
        migrations.RemoveField(
            model_name="ticketcomment",
            name="pub_date",
        ),
    ]
