# Generated by Django 4.2.2 on 2023-07-06 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0003_remove_ticket_pub_date_remove_ticketcomment_pub_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="closed",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="closed_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
