# Generated by Django 4.2.2 on 2023-07-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_ticket_closed_ticket_closed_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticketstatus",
            name="id",
        ),
        migrations.AlterField(
            model_name="ticketstatus",
            name="status",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
