# Generated by Django 4.2.2 on 2023-07-06 05:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_remove_ticketstatus_id_alter_ticketstatus_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="status",
        ),
    ]
