# Generated by Django 4.2.2 on 2023-07-06 06:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_ticket_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="status",
        ),
        migrations.DeleteModel(
            name="TicketStatus",
        ),
    ]
