# Generated by Django 4.2.2 on 2023-07-06 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_remove_ticket_status_delete_ticketstatus"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=20, unique=True)),
                ("description", models.CharField(max_length=200)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="ticket",
            name="status",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to="core.ticketstatus"),
            preserve_default=False,
        ),
    ]
