# Generated by Django 4.2.2 on 2023-07-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_ticketstatus_ticket_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketLabel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=20, unique=True)),
                ("description", models.CharField(max_length=200)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
