# Generated by Django 4.2.2 on 2023-07-07 05:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0010_ticketlabel"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="labels",
            field=models.ManyToManyField(blank=True, related_name="labeled_tickets", to=settings.AUTH_USER_MODEL),
        ),
    ]
