# Generated by Django 4.2.2 on 2023-07-08 02:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_ticket_pub_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="closed",
            new_name="close_date",
        ),
    ]
