# Generated by Django 4.2.2 on 2023-07-08 04:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_rename_closed_ticket_close_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="progress",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
