# Generated by Django 4.2.2 on 2023-07-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_alter_ticketcomment_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketcomment",
            name="pub_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
