# Generated by Django 4.2.2 on 2023-07-20 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_ticketcomment_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketcommentfile",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="core.ticketcomment",
            ),
        ),
        migrations.AlterField(
            model_name="ticketcommentfile",
            name="name",
            field=models.CharField(blank=True, max_length=260),
        ),
    ]
