# Generated by Django 4.2.2 on 2023-07-24 03:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_alter_ticketcommentfile_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketcommentfile",
            name="created",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticketcommentfile",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
