# Generated by Django 4.2.2 on 2023-07-15 10:50

from django.db import migrations, models
import tracker.apps.accounts.models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_customuser_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="position",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(blank=True, upload_to=tracker.apps.accounts.models.profile_img_path),
        ),
    ]
